Repository CS2113-AY1819S2-T09-1/main, pull requests merged in 2019-03, with the labels that each got.

#32 docs/AboutUs: add Ngo Wei Lin's details
  docs/AboutUs.adoc
  docs/images/creastery.png
  docs/team/creastery.adoc
Labels: aspect.Docs, status.ToReview, type.Task

#33 docs: cleanup `AboutUs` documentations
  docs/AboutUs.adoc
  docs/images/damithc.jpg
  docs/images/lejolly.jpg
  docs/images/m133225.jpg
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
  docs/team/chyeo.adoc
  docs/team/lycjackie.adoc
  docs/team/truegitnovice.adoc
  docs/team/wendybaiyunwei.adoc
Labels: aspect.Docs, status.ToReview, type.Task

#36 README.adoc: update AppVeyor CI badge
  README.adoc
Labels: aspect.DevOps, status.ToReview, type.Task

#35 Logic: Improve `FindCommand`
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/module/CodeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/module/CreditsContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/module/KeywordsPredicate.java
  src/main/java/seedu/address/model/module/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/module/CodeContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/module/CreditsContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: status.ToReview, type.Enhancement

#31 README: add UI-mockup
  docs/images/Ui.png
Labels: aspect.Docs, type.Task

#37 Model: depreciate `Email` class
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/Email.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/resources/view/ModuleListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidModuleAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidModuleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateModuleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidModuleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalModulesAddressBook.json
  src/test/java/guitests/guihandles/ModuleCardHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditModuleDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/module/CodeContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/module/EmailTest.java
  src/test/java/seedu/address/model/module/ModuleTest.java
  src/test/java/seedu/address/model/module/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/module/UniqueModuleListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/testutil/EditModuleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/ModuleUtil.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/seedu/address/ui/ModuleListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: status.ToReview, type.Task

#38 README.adoc: update Travis CI badge URL
  README.adoc
Labels: aspect.DevOps, aspect.Docs, status.ToReview, type.Task

#39 docs/images: resize `lycjackie.png`
  docs/images/lycjackie.png
Labels: aspect.Docs, status.ToReview

#41 [#40] Add `_reposense/config.json` to make repository RepoSense-compatible
  .gitignore
  _reposense/config.json
Labels: aspect.DevOps, type.Task

#42 README.adoc: update Coveralls badge URL
  README.adoc
Labels: aspect.DevOps, aspect.Docs, status.ToReview, type.Task

#44 Logic: update command prefixes and usages
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: aspect.UIX, status.ToReview, type.Task

#45 Model/util: update `SampleDataUtil#getSampleModules()`
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: status.ToReview, type.Task

#25 UserGuide: add planner-related details
  docs/UserGuide.adoc
Labels: aspect.Docs, type.Task

#46 Follow upstream master changes: restore original diagrams
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/LogicComponentSequenceDiagram.pptx
Labels: status.ToReview, type.Task

#49 UserGuide: update `Find` command usage
  docs/UserGuide.adoc
Labels: aspect.Docs, type.Task

#50 docs/UserGuide: fix branding & update commands usage and description
  docs/UserGuide.adoc
Labels: aspect.Docs, type.Task

#51 Planner: Refactor parameter 'Year' to 'year'
  src/main/java/seedu/address/model/planner/Year.java
Labels: aspect.CodeQuality, type.Task

#52 docs/team: remove `dataencryption` tag to fix `asciidoctor` warning
  docs/team/chyeo.adoc
  docs/team/creastery.adoc
  docs/team/lycjackie.adoc
  docs/team/truegitnovice.adoc
  docs/team/wendybaiyunwei.adoc
Labels: aspect.Docs

#53 README: update documentation
  README.adoc
Labels: aspect.Docs, type.Task

#47 UserGuide: update degree planner details and FAQ
  docs/UserGuide.adoc
Labels: aspect.Docs, type.Task

#54 DeveloperGuide: add `find` module use case
  docs/DeveloperGuide.adoc
Labels: aspect.Docs, type.Task

#48 UserGuide: update to include 'RequirementCategory' details
  docs/UserGuide.adoc
Labels: aspect.Docs, type.Task

#56 docs/DeveloperGuide: update instructions for manual testing
  docs/DeveloperGuide.adoc
Labels: aspect.Docs, status.ToReview, type.Task

#55 docs/DeveloperGuide: update non functional requirements
  docs/DeveloperGuide.adoc
Labels: aspect.Docs, status.ToReview, type.Task

#58 docs/DeveloperGuide: remove unnecessary sections
  docs/DeveloperGuide.adoc
Labels: aspect.Docs, type.Task

#60 UI: update application title to `PlanWithEase`
  src/main/resources/view/MainWindow.fxml
Labels: aspect.UIX, type.Task

#61 DeveloperGuide: update to reflect the implementations
  docs/DeveloperGuide.adoc
  docs/images/StorageClassDiagram.png
Labels: aspect.Docs, status.ToReview, type.Task

#62 MainApp: bump `MainApp#VERSION` to v1.1.0 for release
  src/main/java/seedu/address/MainApp.java
Labels: status.ToReview, type.Task

#70 UI: update `ModuleCard` and `ModuleListCard.fxml`
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/resources/view/ModuleListCard.fxml
  src/test/java/guitests/guihandles/ModuleCardHandle.java
Labels: aspect.UIX, status.ToReview, type.Task

#76 Model: update `Name#VALIDATION_REGEX`
  src/main/java/seedu/address/model/module/Name.java
  src/test/data/JsonAddressBookStorageTest/invalidModuleAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/module/NameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
Labels: status.ToReview, type.Task

#77 Model: update `Code#VALIDATION_REGEX`
  src/main/java/seedu/address/model/module/Code.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidModuleAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidModuleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateModuleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidModuleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalModulesAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/module/CodeContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/module/CodeTest.java
  src/test/java/seedu/address/model/module/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/seedu/address/ui/ModuleListPanelTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: type.Task

#79 Logic: Fix `FindCommandParser#getKeywordsPredicate(...)`
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: aspect.Testing, status.ToReview, type.Bug

#67 Logic: Improve`FindCommand`
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/module/CodeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/module/CreditsContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/module/KeywordsPredicate.java
  src/main/java/seedu/address/model/module/NameContainsKeywordsPredicate.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: type.Enhancement

#68 docs/UserGuide: update `find` command usage
  docs/UserGuide.adoc
Labels: aspect.Docs, status.ToReview

#69 Storage: combine `VersionedRequirementCategory` into `VersionedAddressBook`
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/ReadOnlyRequirementCategoryList.java
  src/main/java/seedu/address/model/RequirementCategoryList.java
  src/main/java/seedu/address/model/RequirementCategoryModel.java
  src/main/java/seedu/address/model/VersionedRequirementCategoryList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/util/SampleRequirementCategoryUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonRequirementCategoryListStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableModuleList.java
  src/main/java/seedu/address/storage/JsonSerializableRequirementCategoryList.java
  src/main/java/seedu/address/storage/RequirementCategoryListStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonSerializableAddressBookTest/typicalRequirementCategoryAddressBook.json
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/RequirementCategoryBuilder.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/seedu/address/testutil/TypicalRequirementCategories.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SystemTestSetupHelper.java
Labels: status.ToReview, type.Task

#83 Model: update `Credits#VALIDATION_REGEX`
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/module/Credits.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/duplicateModuleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalModulesAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalRequirementCategoryAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/module/CodeContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/module/CreditsContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/module/CreditsTest.java
  src/test/java/seedu/address/model/module/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/RequirementCategoryBuilder.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/seedu/address/testutil/TypicalRequirementCategories.java
  src/test/java/seedu/address/ui/ModuleListPanelTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: status.ToReview, type.Task

#85 Model: update `Module#isSameModule(...)`
  src/main/java/seedu/address/model/module/Module.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/module/ModuleTest.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: status.ToReview, type.Enhancement

#84 Follow upstream master changes: upgrade TestFX dependency to 4.0.15-alpha
  build.gradle
Labels: status.ToReview, type.Task

#86 Follow upstream master changes: edit addresses of Checkstyle DTD files
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
Labels: status.ToReview, type.Task

#87 Follow upstream master changes: rename StringUtilTest#isUnsignedPositiveInteger() to isNonZeroUnsignedInteger()
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: status.ToReview, type.Task

#88 Follow upstream master changes: remove unused ExpectedException in ConfigTest
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: status.ToReview, type.Task

#81 DegreePlanner: add `planner_list_all` command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/PlannerListAllCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/util/SampleDegreePlannerUtil.java
  src/main/java/seedu/address/ui/DegreePlannerCard.java
  src/main/java/seedu/address/ui/DegreePlannerListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/DegreePlannerListCard.fxml
  src/main/resources/view/DegreePlannerListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/PlannerListAllCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: status.ToReview

#91 Model: make `Module` support co-requisites
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonSerializableModuleList.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/resources/view/ModuleListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalModulesAddressBook.json
  src/test/java/guitests/guihandles/ModuleCardHandle.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/seedu/address/ui/ModuleListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: status.ToReview

#98 README: update UI
  docs/images/Ui.png
Labels: aspect.Docs

#101 docs/DeveloperGuide: update module co-requisites implementation details
  docs/DeveloperGuide.adoc
Labels: aspect.Docs, status.ToReview

#99 docs/UserGuide: update module-related command usages
  docs/UserGuide.adoc
Labels: aspect.Docs

#94 UserGuide: update 'planner_list_all'
  docs/UserGuide.adoc
Labels: aspect.Docs

#103 Update on UserGuide to reflect current implementation
  docs/UserGuide.adoc
Labels: aspect.Docs

#107 build.gradle: add `buildJar`, update `archiveName` and dependencies
  build.gradle
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/model/UserPrefs.java
Labels: aspect.DevOps, type.Task

#108 Storage/JsonSerializableAddressBook: address `javac` linter warnings
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: aspect.CodeQuality, status.ToReview, type.Task

#110 Resources/images: Application's icon update
  README.adoc
  copyright.txt
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/plan_with_ease_32.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: aspect.UIX, type.Task

#116 docs/UserGuide: fix repoURL
  docs/UserGuide.adoc
Labels: aspect.Docs, status.ToReview

#75 Combine VersionedDegreePlannerList into VersionedAddressBook
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/PlannerListAllCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/DegreePlannerList.java
  src/main/java/seedu/address/model/DegreePlannerModel.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/ReadOnlyDegreePlannerList.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/VersionedDegreePlannerList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/util/SampleDegreePlannerUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/DegreePlannerListStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonDegreePlannerListStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableDegreePlannerList.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidDegreePlannerAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidDegreePlannerAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalDegreePlannerAddressBook.json
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/PlannerListAllCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/RequirementAddCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/DegreePlannerBuilder.java
  src/test/java/seedu/address/testutil/TypicalDegreePlanners.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SystemTestSetupHelper.java
Labels: type.Task

#114 UI: update on degree planner
  src/main/java/seedu/address/ui/DegreePlannerCard.java
  src/main/java/seedu/address/ui/DegreePlannerListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DegreePlannerListCard.fxml
  src/main/resources/view/DegreePlannerListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: aspect.UIX, type.Task

#117 UI: standardise `saveLocationStatus` path in status bar
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/ui/StatusBarFooterTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: aspect.UIX

#100 docs/DeveloperGuide: update `find` command implementation details
  docs/DeveloperGuide.adoc
  docs/images/FindCommandSequenceDiagram.png
Labels: aspect.Docs, status.ToReview

#118 UI:DegreePlanner: update to display sorted module codes
  src/main/java/seedu/address/ui/DegreePlannerCard.java
Labels: aspect.UIX

#112 Bug fix for command 'requirement_add'
  src/main/java/seedu/address/logic/commands/RequirementAddCommand.java
  src/main/java/seedu/address/logic/parser/RequirementAddCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/requirement/RequirementCategory.java
  src/main/java/seedu/address/model/requirement/UniqueRequirementCategoryList.java
  src/main/java/seedu/address/storage/JsonAdaptedRequirementCategoryList.java
  src/test/data/JsonSerializableAddressBookTest/typicalRequirementCategoryAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RequirementAddCommandTest.java
  src/test/java/seedu/address/testutil/RequirementCategoryBuilder.java
  src/test/java/seedu/address/testutil/TypicalRequirementCategories.java
Labels: severity.High, type.Bug

#105 DeveloperGuide: update on documentation
  docs/DeveloperGuide.adoc
Labels: aspect.Docs, status.ToReview

#121 Model & Storage: add more checks to prevent edge cases
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableDegreePlannerList.java
  src/main/java/seedu/address/storage/JsonSerializableModuleList.java
  src/main/java/seedu/address/storage/JsonSerializableRequirementCategoryList.java
  src/test/data/JsonSerializableAddressBookTest/typicalModulesAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/EditModuleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: aspect.Testing, type.Task

#120 MainApp: bump `MainApp#VERSION` to v1.2.1 for release
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#102 DeveloperGuide: update implementation for 'PlannerList'
  docs/DeveloperGuide.adoc
  docs/images/PlannerListComponentSequenceDiagram.png
Labels: aspect.Docs, status.ToReview

#122 Model & Storage: add more checks to co-requisites cascading
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
Labels: aspect.Testing, status.ToReview, type.Task

#131 Model/util: update `SampleDataUtil#getSampleDegreePlanners()`
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: status.ToReview, type.Task

#134 Model/util: add and use `InitialDataUtil` class
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/InitialDataUtil.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
Labels: aspect.UIX, type.Task

#135 Model: update `Name#VALIDATION_REGEX` and `Name#MESSAGE_CONSTRAINTS`
  src/main/java/seedu/address/model/module/Name.java
Labels: status.ToReview, type.Task

#137 test/CommandParserTestUtil: address `javac` linter warnings
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
Labels: aspect.CodeQuality, type.Task

#138 Model/module: update `Module#toString()`
  src/main/java/seedu/address/model/module/Module.java
Labels: aspect.UIX, type.Task

#143 Logic/commands: update `ClearCommand#MESSAGE_SUCCESS`
  src/main/java/seedu/address/logic/commands/ClearCommand.java
Labels: aspect.UIX, type.Task

#141 Logic/command: update `HistoryCommand#execute(...)` & error message
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/HistoryCommandTest.java
Labels: aspect.CodeQuality, aspect.UIX, type.Task

#142 Logic: update `DeleteCommand` success and error messages
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
Labels: aspect.CodeQuality, aspect.UIX, status.ToReview, type.Task

#140 Logic: update `AddCommand` success and error messages
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: aspect.CodeQuality, aspect.UIX, status.ToReview, type.Task

#139 Logic: update `EditCommand` success and error messages
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: aspect.CodeQuality, aspect.UIX, status.ToReview, type.Task

#133 RequirementCategory: implement `requirement_list` command
  src/main/java/seedu/address/logic/commands/PlannerMoveCommand.java
  src/main/java/seedu/address/logic/commands/RequirementListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/DegreePlannerCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/RequirementCategoryCard.java
  src/main/java/seedu/address/ui/RequirementCategoryListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DegreePlannerListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RequirementCategoryListCard.fxml
  src/main/resources/view/RequirementCategoryListPanel.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalRequirementCategoryAddressBook.json
  src/test/java/guitests/guihandles/ModuleCardHandle.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RequirementListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/module/UniqueModuleListTest.java
  src/test/java/seedu/address/testutil/TypicalRequirementCategories.java
Labels: status.ToReview
